language: python

python:
  - "3.5"

sudo: required
dist: trusty

env:
  - TRAVIS_NODE_VERSION="4"

addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver

services:
  - postgresql

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser

install: 
  - pip install -r requirements/CI.txt
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - npm install -g csslint

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
  - flake8
  - python manage.py migrate

script:
  - coverage run --source="." manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)